train: []
test:
  batch:
    - _target_: src.metrics.Accuracy
      name: "Accuracy"
  epoch:
    - _target_: src.metrics.EER
      name: "EER"
inference:
  batch:
    - _target_: src.metrics.Accuracy
      name: "Accuracy"
  epoch:
    - _target_: src.metrics.EER
      name: "EER"