defaults:
   - datasets: utsig
   - transforms: main
   - model: convnext-tiny
   - loss: binary_loss
   - _self_

dataloaders:
   _target_: torch.utils.data.DataLoader
   batch_size: 10
   num_workers: 2
   pin_memory: True

trainer:
   device: auto
   seed: 42
   split: 0.8
   