defaults:
   - datasets: utsig
   - transforms: main
   - model: convnext-tiny
   - loss: binary_loss
   - metrics: accuracy
   - _self_

dataloaders:
   _target_: torch.utils.data.DataLoader
   batch_size: 10
   num_workers: 2
   pin_memory: True

train_test_split: 0.8

writer: 
   _target_: src.logger.WandBWriter
   project_name: "offline-signature-verification"
   entity: null
   run_name: "first-run"
   mode: "online"
   loss_names: ["loss"]
   log_checkpoints: False
   id_length: 8

optimizer: 
   _target_: torch.optim.AdamW
   lr: 3e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}

trainer:
   seed: 42
   epoch_len: 500
   log_step: 50
   device: auto
   save_dir: "saved"
   resume_from: null
   override: False
   