defaults:
   - dataset_downloaders: gpds_synthetic
   - transforms: main
   - model: convnext-tiny
   - loss: cross_entropy_loss
   - metrics: metrics
   - writer: wandb
   - lr_scheduler: step_lr
   - preprocessor: no_preprocessor
   - _self_

preprocess: False

dataloaders:
   _target_: torch.utils.data.DataLoader
   batch_size: 32
   num_workers: 2
   pin_memory: True

train_test_split:
   split: 0.9
   shuffle: True

optimizer: 
   _target_: torch.optim.AdamW
   lr: 1e-5

trainer:
   seed: 42
   epoch_len: null
   n_epochs: 50
   log_step: 500
   monitor: "max test_Accuracy"
   early_stop: ${trainer.n_epochs}
   device: auto
   device_tensors: ["img", "labels"]
   save_dir: "saved"
   save_period: 5
   max_grad_norm: null
   resume_from: null
   override: False
   