defaults:
   - dataset: gpds_synthetic
   - transforms: with_preprocess
   - model: convnext-tiny
   - loss: cross_entropy_loss
   - metrics: metrics
   - writer: wandb
   - lr_scheduler: step_lr
   - preprocessor: htcsignet
   - _self_

dataloaders:
   _target_: torch.utils.data.DataLoader
   batch_size: 32
   num_workers: 2
   pin_memory: True

train_test: 
   split: 0.8
   users: [301, 1000]

optimizer: 
   _target_: torch.optim.AdamW
   lr: 1e-5

trainer:
   seed: 42
   epoch_len: null
   n_epochs: 50
   log_step: 500
   monitor: "min test_EER"
   early_stop: ${trainer.n_epochs}
   device: auto
   device_tensors: ["img", "labels"]
   save_dir: "saved"
   save_period: 5
   max_grad_norm: null
   resume_from: null
   override: False
   