defaults:
   - dataset_downloaders: gpds_synthetic
   - transforms: main
   - model: convnext-tiny
   - loss: cross_entropy_loss
   - metrics: accuracy
   - _self_

dataloaders:
   _target_: torch.utils.data.DataLoader
   batch_size: 16
   num_workers: 2
   pin_memory: True

train_test_split:
   split: 0.8
   shuffle: True

writer: 
   _target_: src.logger.WandBWriter
   project_name: "offline-signature-verification"
   entity: null
   run_name: "first-run"
   mode: "online"
   loss_names: ["loss"]
   log_checkpoints: False
   id_length: 8

optimizer: 
   _target_: torch.optim.AdamW
   lr: 1e-5

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}

trainer:
   seed: 42
   epoch_len: 100
   n_epochs: 500
   log_step: 50
   monitor: "max test_Accuracy"
   early_stop: ${trainer.n_epochs}
   device: auto
   device_tensors: ["img", "labels"]
   save_dir: "saved"
   save_period: 5
   max_grad_norm: 1
   resume_from: null
   override: False
   