defaults:
  - dataset: gpds_synthetic
  - transforms: with_preprocess
  - model: convnext-21k
  - loss: cross_entropy_loss
  - metrics: metrics
  - preprocessor: htcsignet 
  - _self_

dataloaders:
   _target_: torch.utils.data.DataLoader
   batch_size: 32
   num_workers: 2
   pin_memory: True

embeddings:
  pretrained_paths: ["saved/SconvnextB_infer/model_best.pth"]
  save_dir: null
  filename: "SconvnextB_infer_dist.npz"

train_test:
  users: [301, 1000]
  split: 0.9

test:
  users: [1, 300]

device:
  device: "auto"
  device_tensors: ["reference", "sig", "labels"]

seed: 42

catboost:
  _target_: catboost.CatBoostClassifier
  task_type: "CPU"
  iterations: 1000
  learning_rate: 1e-4
  depth: 8
  use_best_model: True
  eval_metric: "Accuracy"
  early_stopping_rounds: 50
  random_seed: 42
  