defaults:
  - dataset: cedar
  - transforms: with_preprocess
  - model: convnext-21k
  - metrics: catboost
  - preprocessor: htcsignet 
  - _self_

mode: "standalone"

dataloaders:
   _target_: torch.utils.data.DataLoader
   batch_size: 32
   num_workers: 2
   pin_memory: True

embeddings:
  from_pretrained: "saved/convnext_cedar/model_best.pth"
  device_tensors: ["img", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"

train_data:
  modes: ["singles", "singles"]
  users: [1, 50]
  split: 0.9

test_data:
  mode: "pairs"
  users: [51, 55]

seed: 42

catboost:
  save_filename: null
  from_pretrained: null
  task_type: "CPU"
  iterations: 1000
  learning_rate: 1e-4
  depth: 8
  use_best_model: True
  eval_metric: "Accuracy"
  early_stopping_rounds: 50
  random_seed: 42
  