defaults:
  - model: coatnet-base
  - dataset: cedar # we do not want to run inference on training data
  - transforms: with_preprocess
  - preprocessor: htcsignet
  - classifier: cosine
  - _self_

mode: "standalone"

seed: 42

dataloaders:
   _target_: torch.utils.data.DataLoader
   batch_size: 32
   num_workers: 2
   pin_memory: True

data:
  users: [51, 55]
  mode: "singles"

embeddings:
  from_pretrained: "saved/coatnetB-0.9split/model_best.pth"
  device_tensors: ["img", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"