defaults:
  - model: coatnet-base
  - metrics: metrics
  - dataset: gpds_synthetic # we do not want to run inference on training data
  - transforms: with_preprocess
  - preprocessor: htcsignet
  - _self_

mode: "standalone"

dataloaders:
   _target_: torch.utils.data.DataLoader
   batch_size: 32
   num_workers: 2
   pin_memory: True

data:
   users: [1, 300]
   mode: "singles"

inferencer:
  device_tensors: ["img", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "utsig" # any name here, can be a dataset name
  seed: 42
  from_pretrained: "saved/coatnetB-0.9split/model_best.pth" # path to the pretrained model
