_target_: src.classifiers.EuclideanClassifier
num_steps: 200
m_values: [1, 12]
device_tensors: ["img", "labels"] # which tensors should be on device (ex. GPU)
device: auto # device name or "auto"
from_pretrained: "saved/coatnetB-0.9split/model_best.pth"