train:
  img:
    _target_: torchvision.transforms.Compose
    transforms: 
      - _target_: torchvision.transforms.ToPILImage
      - _target_: torchvision.transforms.RandomCrop
        size: [224, 224]
      - _target_: torchvision.transforms.ToTensor
      - _target_: src.transforms.GrayscaleToRGB
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  
test:
  img:
    _target_: torchvision.transforms.Compose
    transforms: 
      - _target_: torchvision.transforms.ToPILImage
      - _target_: torchvision.transforms.CenterCrop
        size: [224, 224]
      - _target_: torchvision.transforms.ToTensor
      - _target_: src.transforms.GrayscaleToRGB
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  