train:
  img:
    _target_: torchvision.transforms.Compose
    transforms: 
      - _target_: torchvision.transforms.ToPILImage
      - _target_: torchvision.transforms.RandomCrop
        size: [224, 224]
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.0164]
        std: [0.0950]
  
test:
  img:
    _target_: torchvision.transforms.Compose
    transforms: 
      - _target_: torchvision.transforms.ToPILImage
      - _target_: torchvision.transforms.CenterCrop
        size: [224, 224]
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.0164]
        std: [0.0950]
  