train:
  img:
    _target_: torchvision.transforms.Compose
    transforms: 
      - _target_: torchvision.transforms.ToPILImage
      - _target_: torchvision.transforms.RandomCrop
        size: [224, 224]
      - _target_: torchvision.transforms.ToTensor
  
test:
  img:
    _target_: torchvision.transforms.Compose
    transforms: 
      - _target_: torchvision.transforms.ToPILImage
      - _target_: torchvision.transforms.CenterCrop
        size: [224, 224]
      - _target_: torchvision.transforms.ToTensor
  