img:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Resize
      size: [224, 224]
      interpolation: 3
    - _target_: torchvision.transforms.RandomRotation
      degrees: 40
    - _target_: torchvision.transforms.RandomAffine
      degrees: 0
      translate: [0.2, 0.2]
      shear: 20
      scale: [0.8, 1.2]
    - _target_: torchvision.transforms.ColorJitter
      brightness: 0.2
      contrast: 0.2
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.449]
      std: [0.226]